# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('config.py', '.'),
        ('utils.py', '.'),
        ('requirements.txt', '.'),
        ('SampleFirmware', 'SampleFirmware'),
        ('README.md', '.'),
        ('README_ENHANCED.md', '.'),
        ('25_ICS_SUPPORT_COMPLETE.md', '.'),
        ('DAT_FILE_ENHANCEMENTS.md', '.'),
        ('ENHANCED_FEATURES_SUMMARY.md', '.'),
        ('UI_IMPROVEMENTS_IMPLEMENTED.md', '.'),
        ('VALIDATION_SYSTEM_SUMMARY.md', '.'),
        ('FIRMWARE_VALIDATION_README.md', '.'),
        ('ENHANCED_RESET_FEATURES.md', '.'),
        ('ENHANCED_UPLOADER_IMPROVEMENTS.md', '.'),
        ('PROJECT_STRUCTURE.md', '.'),
        ('COMPLETE_FUNCTIONAL_OVERVIEW.md', '.'),
        ('UI_LAYOUT_DESCRIPTION.md', '.'),
        ('UI_UX_IMPROVEMENTS_SUMMARY.md', '.'),
        ('PIXEL_FIX_CHECKLIST.txt', '.'),
        ('GIT_COMMANDS.txt', '.'),
        ('version_info.txt', '.'),
    ],
    hiddenimports=[
        'PIL',
        'PIL._tkinter_finder',
        'numpy',
        'serial',
        'serial.tools.list_ports',
        'esptool',
        'tkinter',
        'tkinter.ttk',
        'tkinter.filedialog',
        'tkinter.messagebox',
        'tkinter.colorchooser',
        'threading',
        'subprocess',
        'datetime',
        'importlib.util',
        'zipfile',
        'tempfile',
        'urllib.request',
        'platform',
        'shutil',
        'json',
        're',
        'sys',
        'os',
        'time',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='J_Tech_Pixel_Uploader_v3.0',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
    version_file=None,
)
